name: PR CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          check-latest: true
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    runs-on: ubuntu-latest
    env:
      PANGEA_DOMAIN: ${{ env.PANGEA_TOKEN }}
      PANGEA_TOKEN: ${{ secrets.PANGEA_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - run: deno lint
      - run: make test
