name: PR CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          check-latest: true
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  
  test:
    needs: lint
    runs-on: ubuntu-latest
    env:
      PANGEA_TOKEN: ${{ secrets.PANGEA_TOKEN }}
      PANGEA_ENTENSION: ${{ github.workspace }}/pangea.so
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          check-latest: true
      - run: go test ./...
